info:
  contact: {}
paths:
  /index:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 扶뒬못
  /user/GetUserList:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      tags:
      - 扶뒬못
swagger: "2.0"
